name: バグの報告
description: 改善のためのバグの報告
labels: [Bug]
body:
  - type: textarea
    id: description
    attributes:
      label: バグの説明
      description: バグについての説明を明確かつ簡潔に記述してください。
    validations:
      required: true
  - type: textarea
    id: process
    attributes:
      label: バグを引き起こす手順
      description: バグを引き起こす手順を書いてください。
      value: |
        例
        1. 起動する
        2. "コンフィグ"を選択する
        3. "Exit"を選択する
        4. エラーが発生する
    validations:
      required: true
  - type: textarea
    id: enviroment
    attributes:
      label: 環境
      description: バグが起こった環境を書いてください。
      value: |
        例
        OS: Windows 10 Pro Version 21H1
        CPU: Intel Core i7-10700K
        RAM: 32GB
        GPU: iGPU
        Version: 1.7.1.5
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: スクリーンショット
      description: 必要に応じて、問題を説明するためのスクリーンショットを添付してください。
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: 追加情報
      description: 必要に応じて、追加情報を書いてください。
    validations:
      required: false
