name: Request
description: Create a request 
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the request
      description: A clear and concise description of what the request is.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
