name: build

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [win-x86, win-x64, linux-x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set REV_LIST_COUNT
      id: rev
      run: |
        cd ${{ github.workspace }}
        REVCOUNT=`git rev-list --count HEAD`
        echo "::set-output name=REV_LIST_COUNT::${REVCOUNT}"
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish TJAPlayer3 -o Test/net5.0 -r ${{ matrix.platform }} -p:PublishSingleFile=true --configuration Release --self-contained true
    - name: Remove File
      uses: JesseTG/rm@v1.0.0
      with:
        path: Test/net5.0/${{matrix.platform}}
    - name: Remove Directory
      run: |
        cd ${{ github.workspace }}
        cd Test/net5.0/ffmpeg
        echo for %%i in (*) do ( > remove.bat
        echo if not %%i==${{matrix.platform}} rd /s /q %%i >> remove.bat
        echo ) >> remove.bat
        echo del remove.bat >> remove.bat
        remove.bat

    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: TJAPlayer3-f-Release-${{ matrix.platform }}-${{ steps.rev.outputs.REV_LIST_COUNT }}
        path: Test
